apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
     app: my-app
spec:
    containers:
      - name: my-cont
        image: httpd
        ports:  
        - containerPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: dev
  labels:
     env: dev
spec:
    containers:
      - name: my-container2
        image: httpd
        ports:  
        - containerPort: 80        
---

apiVersion: v1
kind: Pod
metadata:
  name: prod
  labels:
     env: Prod
spec:
    containers:
      - name: my-container3
        image: httpd
        ports:  
        - containerPort: 80 