apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  replicas: 3
  selector:
    app: my-app
  template:
    metadata:
      name: httpd
      labels:
        app: my-app
    spec:
      containers:
      - name: my-cont1
        image: httpd
        ports:
        - containerPort: 80
