version: "3.8"

services:
  backend:
    build:
      context: ./spring-backend
    container_name: backend-app
    ports:
      - "8080:8080"
    
  frontend:
    build:
      context: ./angular-frontend 
    container_name: frontend-app
    ports:
      - "80:80"
    
