# Use the official Apache HTTPD image as the base image
FROM httpd:alpine

# Copy the index.html file to the Apache HTML directory
COPY index.html /usr/local/apache2/htdocs/index.html

# Expose port 80 for the web server
EXPOSE 80